<a href="https://colab.research.google.com/github/ArshadAbdullah27/data_science_week1/blob/main/numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
a=np.array([[1,2],[3,5]])
print(a)
print(a.shape)

[[1 2]
 [3 5]]
(2, 2)


create a random numpy array of size 3*4


In [4]:
b=np.random.random((3,4))
print(b)
print(b.shape)

[[0.61486703 0.38393445 0.00751627 0.39393798]
 [0.20889278 0.22326023 0.5801142  0.49342727]
 [0.74640938 0.56488444 0.23128354 0.05918496]]
(3, 4)


create a numpy array of ones and a numpy array of zeroes

In [11]:
import numpy as np


In [15]:
c=np.ones((2,2))
d=np.zeros((2,2))
print("\n.Array of ones(2*2): \n", c)
print("\n.Array of zeroes: \n" , d)


.Array of ones(2*2): 
 [[1. 1.]
 [1. 1.]]

.Array of zeroes: 
 [[0. 0.]
 [0. 0.]]


create a random numpy array of size(6*3) and transpose it

In [16]:
e = np.random.random((6,3))
transposed = e.T
print("\n6*3 Random Array: \n", e)
print("\nTransposed (3*6): \n", transposed)


6*3 Random Array: 
 [[0.59179429 0.68768596 0.4643029 ]
 [0.16187715 0.77833401 0.66391162]
 [0.2440686  0.62149014 0.09293534]
 [0.58602941 0.67561945 0.72212595]
 [0.86082687 0.911091   0.85264945]
 [0.35262933 0.26569996 0.85662721]]

Transposed (3*6): 
 [[0.59179429 0.16187715 0.2440686  0.58602941 0.86082687 0.35262933]
 [0.68768596 0.77833401 0.62149014 0.67561945 0.911091   0.26569996]
 [0.4643029  0.66391162 0.09293534 0.72212595 0.85264945 0.85662721]]


Create two random numpy array of size (n*p) and (p*m) then compute the dot products

In [18]:
n, p, m = 2,3,4
F = np.random.random((n,p))
G = np.random.random((p,m))
dotproducts = np.dot(F, G)

print("\nF (n * p)\n", F)
print("\nG (p * n)\n" , G)
print("\nDot Products:\n" , dotproducts)


F (n * p)
 [[0.7989442  0.68603226 0.6256114 ]
 [0.9107553  0.10599464 0.54370489]]

G (p * n)
 [[0.30290747 0.80343141 0.64043857 0.08139961]
 [0.58020376 0.3015511  0.72196227 0.69755296]
 [0.12444896 0.0931846  0.24644668 0.2393183 ]]

Dot Products:
 [[0.71790135 0.90706799 1.16114394 0.69329784]
 [0.40503658 0.81435714 0.79380122 0.27819053]]
